theme: jekyll-theme-cayman
title: RunarSF
description: Slowly trying to figure out the concept of Processing. Norwegian coffee lover, keyboard enthusiast and IT student that enjoys messing around with code.
show_downloads: false
