FROM python

RUN apt-get update && \
	apt-get install git -y && \
	apt-get install python3 -y && \
	apt-get install python3-pip -y

COPY ./src/requirements.txt /startpage/requirements.txt
RUN python3 -m pip install -U -r /startpage/requirements.txt

WORKDIR /startpage

CMD ["python3", "-u", "api.py"]
